### ISSUE TITLE
cffi ?

### ISSUE THREAD

**Issue by stuaxo** [ldo/qahirah#1]
Would you consider moving to CFFI in the future?

It's supposed to be much more performant in Pypy.   OTOH, I realise this would be quite a big step.

https://mail.python.org/pipermail/pypy-dev/2012-December/010719.html

http://eli.thegreenplace.net/2013/03/09/python-ffi-with-ctypes-and-cffi

**Comment by ldo** [comment]
No.

**Comment by stuaxo** [comment]
Cheers :)
