### ISSUE TITLE
Support rendering LaTeX symbols?

### ISSUE THREAD

**Issue by neozhaoliang** [ldo/qahirah#13]
Hi, does qahirah support rendering latex equations to the SVGSurface? (if the user has LaTeX environment installed on the machine)

**Comment by ldo** [comment]
Is there a [Cairo API](https://www.cairographics.org/manual/) for that?

**Comment by neozhaoliang** [comment]
The manim cairo backend used latex to compile the tex string and generate the SVG image, and then embed the path to the output image:
https://github.com/3b1b/manim/blob/cairo-backend/manimlib/mobject/svg/tex_mobject.py

**Comment by ldo** [comment]
Qahirah is a Cairo wrapper, not a Latex wrapper.
