### ISSUE TITLE
Rename README to README.md

### ISSUE THREAD

**Issue by silversquirl** [ldo/qahirah#4]
If you make it a Markdown file (it currently uses Markdown syntax, but doesn't have the extension), GitHub will render said Markdown to HTML and display it with nice formating.

Currently, it's just rendered as plain text which, while not a big issue, isn't as nice to read.

**Comment by ldo** [comment]
It is traditional for the file to be called `README`. Having to put a `.md` extension on the end is a GitHubism.

**Comment by silversquirl** [comment]
READMEs using plain text _are_ usually called `README`, but using an extension does provide some additional context for people reading it. If they know it's Markdown, they might want to pass it through a Markdown -> HTML converter beforehand, for example.

**Comment by silversquirl** [comment]
Also, in this particular case, you're _using GitHub_, so it makes sense to use GitHubisms anyway.

If you're still against renaming the file, perhaps provide a symlink from `README.md` to `README`, so that GitHub can detect the filetype.
