### ISSUE TITLE
Small changes to work on macos/openbsd

### ISSUE THREAD

**Issue by since19861019** [ldo/qahirah#6]
Thank you for a great library!
I was searching for a python cairo/freetype library for macos/openbsd and found your file can be easily adapted to work on them as follows. (the same code works on freetype2.py)
Will you incorporate this kind of small cross-paltform code ?
...
import sys
SYSLIB_LINUX = ["libc.so.6","libfreetype.so.6","libfontconfig.so.1","libcairo.so.2"]
SYSLIBS = {
	"darwin":["libc.dylib","libfreetype.dylib","libfontconfig.dylib","libcairo.dylib"],
	"openbsd6":["libc.so","libfreetype.so","libfontconfig.so","libcairo.so"],
}.get(sys.platform,SYSLIB_LINUX)

cairo = ct.cdll.LoadLibrary(SYSLIBS[3])
...

**Comment by ldo** [comment]
Did you notice why the Linux libraries have «name».so.«n» and not just «name».so?

**Comment by since19861019** [comment]
For API compatibility, I guess.

In my message, I just copied & pasted the original library names for Linux not to break the code.
It is just an example, but if you have a single placeholder for other platforms, it is convenient when I have to patch the code later.

In OpenBSD 6.x ("openbsd6"), all the lib numbers are greater than the ones in your file, so I just omitted them, expecting they are backward compatible and just run it to see if it works.
They are libc.so.90.0.a, libcairo.so.12.3, libfontconfig.so.11.0, libfreetype.so.28.1 in OpenBSD 6.2.

As for macos, libc.dylib does not have numbers and the other libraries are the same as yours. i.e. libcairo.2.dylib, libfontconfig.1.dylib, libfreetype.6.dylib in macos 13.2 + homebrew.

**Comment by ldo** [comment]
OK, how about this for supporting OpenBSD.

[openbsd6.patch.txt](https://github.com/ldo/qahirah/files/1609430/openbsd6.patch.txt)

I want to avoid macOS.

**Comment by since19861019** [comment]
Yes, it works.
I hope you will make the same modification to freetype2.py

**Comment by ldo** [comment]
Open an issue and I’ll post a patch to test.

**Comment by ldo** [comment]
Patch committed to master.
